version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306"
###< doctrine/doctrine-bundle ###

###> LDAP server ###
  openldap:
    ports:
      - '1389'
      - '1636'
###< LDAP server ###