controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

redirect_to_home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app_home'

redirect_to_home_2:
    path: /app
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app_home'

redirect_to_default_login:
    path: /login
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app_basic_login'